import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '@/styles/About.module.css';
import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';

export default function About() {
    return (
    <>
        <Head>
            <title>James Yab Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="stylesheet" href="https://use.typekit.net/aih5bul.css"></link>
        </Head>
        <main>
            <Navigation />
            <h1 className="title">About <br></br><span className={styles.highlight}>James Yab</span></h1>
            <p>&emsp;I’m a B.S.C.S. junior at the University of South Florida currently looking for an internship opportunity.  Whether I’m working on new projects or playing video games, I like to spend quite a lot of time looking at a screen.</p>

            <p>&emsp;When I’m not looking at a screen, I’m stuffing my face with food or exploring around to find even more food.</p>
        </main>
        <Footer />
    </>
    )
}