import Head from 'next/head';
import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';
import ContactForm from '@/components/ContactForm';
import Link from 'next/link';
import { HiDocumentSearch, HiOutlineMail } from 'react-icons/hi';
import { ImLinkedin2 } from 'react-icons/im';
import { Button } from 'flowbite-react';

export default function Contact() {

  function ResumeButton() {
    return (
      <Button className="hover:underline my-3" size="md">
        
        <Link target="_blank" href="/James%20Resume.pdf" className="flex items-start">
       
          <HiDocumentSearch size={15} className="mr-1 -ml-1"/>
            View my resume
          
        </Link>

      
      </Button>
    )
  }
  return (
    <>
    <Head>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <Navigation />
      <section className="section--container">
        <h1 className="title">Contact Me</h1>
        <ContactForm />
      </section>
      <section className="section--container">
        <h2 className="section--title">Links</h2>
          <ResumeButton />  
        <Link href="https://www.linkedin.com/in/james-yab" className="inline-flex link">
            <ImLinkedin2 size={20} className="mr-1"/>
              <span className="pt-0.5">LinkedIn</span>
        </Link>
        <br></br>
        <Link href="mailto:jamesy148@usf.edu" className="inline-flex link">
          <HiOutlineMail size={20} className="mr-1"/>
            jamesy148@usf.edu
        </Link>
      </section>

    </main>
    <Footer />
    </>
  )
}
