import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import { Navigation } from '@/components/Navigation';

export default function Home() {
  function handleClick(e) {
    console.log('The link was clicked.', e);
  }

  return (
    <>
      <Head>
        <title>James Yab Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <header className={styles.header}>
        <Navigation />
        </header>
        <div className="hero">
          <h1 className="title">I&apos;m <br></br>James Yab</h1>
          <sub className="subtitle">Frontend Web Developer and <br></br>Software Engineer</sub>
          <p>I am passionate about creating engaging and user-friendly experiences that meet the needs of  users.</p>
        </div>
      </main>
    </>
  )
}
